{% set name = "patatt" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mirrors.edge.kernel.org/pub/software/devel/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a5b7511d9694a3448f25cc7db2df545605fcbadd5dd509484b656f5be123e56d

build:
  entry_points:
    - patatt=patatt:command
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - pynacl

test:
  imports:
    - patatt
  commands:
    - pip check
    - patatt --help
  requires:
    - pip

about:
  home: https://git.kernel.org/pub/scm/utils/patatt/patatt.git/about/
  summary: A simple library to add cryptographic attestation to patches sent via email
  description: |
    This utility allows an easy way to add end-to-end cryptographic attestation
    to patches sent via mail. It does so by adapting the DKIM email signature
    standard to include cryptographic signatures via the X-Developer-Signature
    email header.

    If your project workflow doesn't use patches sent via email, then you don't
    need this and should simply start signing your tags and commits.
  license: MIT
  license_family: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - blmaier
